# Generated by Django 5.0.3 on 2024-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='book_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
